spring:

  application:
    name: transfer-service

  datasource:
    url: jdbc:mysql://localhost:3306/transfer
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: false

customer:
  service:
    url: http://localhost:8080

account:
  service:
    url: http://localhost:8082

card:
  service:
    url: http://localhost:8083


server:
  port: 8081
